config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show] do
    resources :items
  end

  get 'welcome/index'

  get 'welcome/about'

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource_or_scope)
      current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "To-do was saved."
      redirect_to current_user
    else
      flash[:alert] = "There was an error saving the to-do. Please try again."
      redirect_to current_user
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "To-do done!"
    else
      flash.now[:alert] = "Error deleting. Please try again"
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user

    if @user.nil?
      redirect_to new_user_registration_path
    end 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-md-6">
   <%= form_for [@user, Item.new] do |f| %>
     <div class="form-group">
       <%= f.text_field :name, class: 'form-control', placeholder: "Create To-do" %>
     </div>
     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-primary' %>
     </div>
   <% end %>
 </div>
</div>

app/views/items/_item.html.erb
<div class="row">
  <div class="col-md-6">
    <ul class="list-group">
    <li class="list-group-item" id="<%= item.id %>">
      <b><%= item.name %></b>
      <%= link_to "", [item.user, item], remote: true, method: :delete, class: 'glyphicon glyphicon-ok' %>
    <small>Item will be deleted automatically in <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %></small>
    </li>
  </ul>
  </div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.js.erb
$("li#<%= @item.id %>").slideUp();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body
   <div class="container">
      <ul class="nav nav-tabs">
       <li><%= link_to "Home", welcome_index_path %></li>
     </ul>
    <div class="pull-right">
     <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong>
        <%= link_to 'My Profile', user_session_path, :class => 'navbar-link' %> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
     <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
     <% end %>
   </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<div>
  <h2><% @user.email %> To-do</h2>
</div

<div>
    <% @user.items.each do |item| %>
      <%= render item %>
    <% end %>
</div>

<div>
  <%= render partial: 'items/form', locals: { item: @item } %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Blocitoff</h1>
</div>